#!/usr/bin/env python3

import argparse
import logging
import os
import re
import tempfile
import timeit
import subprocess
import yaml
from pathlib import Path

from easydock.auxiliary import expand_path, resolve_path
from easydock.dock.preparation_for_docking import ligand_preparation, pdbqt2molblock


class RawTextArgumentDefaultsHelpFormatter(argparse.RawTextHelpFormatter, argparse.ArgumentDefaultsHelpFormatter):
    pass


def __get_pdbqt_and_score(ligand_out_fname):
    with open(ligand_out_fname) as f:
        pdbqt_out = f.read()
    match = re.search(r'REMARK VINA RESULT:\s+(-?[\d.]+)', pdbqt_out)
    if match:
        score = round(float(match.group(1)), 3)
    else:
        score = None

    return score, pdbqt_out


def mol_dock(mol, config, ring_sample=False):
    """

    :param mol: RDKit Mol of a ligand with title
    :param config: yml-file with docking settings
    :param ring_sample: whether to sample saturated rings and dock multiple starting conformers
    :return:
    """
    config = __parse_config(config)

    mol_id = mol.GetProp('_Name')
    ligand_pdbqt_list = ligand_preparation(mol, boron_replacement=True, ring_sample=ring_sample)

    if ligand_pdbqt_list is None:
        return mol_id, None

    dock_output_conformer_list = []
    start_time = timeit.default_timer()
    for ligand_pdbqt in ligand_pdbqt_list:
        
        # Unidock-pro requires a directory to save outputs and a ligand index file
        ligand_fd, ligand_fname = tempfile.mkstemp(suffix='_ligand.pdbqt', text=True)
        index_fd, index_fname = tempfile.mkstemp(suffix='_index.txt', text=True)
        out_dir = tempfile.mkdtemp(suffix='_unidock_out')

        try:
            with open(ligand_fname, 'wt') as f:
                f.write(ligand_pdbqt)
            
            with open(index_fname, 'wt') as f:
                f.write(ligand_fname + '\n')

            cmd = [
                config["script_file"],
                "--receptor", config["protein"],
                "--ligand_index", index_fname,
                "--dir", out_dir,
                "--search_mode", config.get("search_mode", "balance"),
                "--config", config["protein_setup"]
            ]
            
            if "exhaustiveness" in config:
                cmd += ["--exhaustiveness", config["exhaustiveness"]]
            if "n_poses" in config:
                cmd += ["--num_modes", config["n_poses"]]
            if "seed" in config:
                cmd += ["--seed", config["seed"]]
            # Note: Unidock is GPU accelerated, CPU threads might not be strictly needed, but let's allow it
            if "ncpu" in config:
                cmd += ["--cpu", config["ncpu"]]
                
            cmd = ' '.join(map(str, cmd))

            subprocess.run(cmd, shell=True, check=True, capture_output=True, text=True)

            # Find the output file generated by Unidock in out_dir
            # Output naming convention for Unidock: <ligand_basename>_out.pdbqt
            ligand_basename = Path(ligand_fname).stem
            output_fname = os.path.join(out_dir, f"{ligand_basename}_out.pdbqt")

            if os.path.isfile(output_fname):
                score, pdbqt_out = __get_pdbqt_and_score(output_fname)
                mol_block = pdbqt2molblock(pdbqt_out.split('MODEL')[1], mol, mol_id)

                dock_output = {'docking_score': score,
                               'raw_block': pdbqt_out,
                               'mol_block': mol_block}

                dock_output_conformer_list.append(dock_output)

        except subprocess.CalledProcessError as e:
            logging.warning(f'(unidock) Error caused by docking of {mol_id}\n'
                            f'{str(e)}\n')
        except Exception as e:
            logging.warning(f'(unidock) Unexpected error caused by docking of {mol_id}\n'
                            f'{str(e)}\n')

        finally:
            os.close(ligand_fd)
            os.close(index_fd)
            os.unlink(ligand_fname)
            os.unlink(index_fname)
            # Cleanup the output directory and its contents
            for f in os.listdir(out_dir):
                os.unlink(os.path.join(out_dir, f))
            os.rmdir(out_dir)

    dock_time = round(timeit.default_timer() - start_time, 1)

    logging.debug(f'(unidock) {mol_id}, docked nconf {len(dock_output_conformer_list)}')

    if dock_output_conformer_list:
        output = min(dock_output_conformer_list, key=lambda x: x['docking_score'])
        output['dock_time'] = dock_time
    else:
        output = None

    return mol_id, output


def __parse_config(config_fname):
    with open(config_fname) as f:
        config = yaml.safe_load(f)
    config_dir = os.path.dirname(os.path.abspath(config_fname))
    for arg in ['protein', 'protein_setup', 'script_file']:
        config[arg] = resolve_path(config[arg], config_dir)

    return config
